version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: ./etc/dockerize/backend/Dockerfile
    image: 'php:8.0-fpm'
    volumes:
      - '.:/var/www/html'
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

  mysql:
    image: 'mysql:8.0'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - './.data/mysql:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - app-network

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - app-network

  node:
    image: 'node:14-alpine'
    volumes:
      - './frontend:/app'
    working_dir: '/app'
    command: 'npm run serve'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql:
